Cleanup arch-linux-bootstrap and set default paths

diff --git a/arch-linux-bootstrap/arch-linux-bootstrap b/arch-linux-bootstrap/arch-linux-bootstrap
--- a/arch-linux-bootstrap/arch-linux-bootstrap
+++ b/arch-linux-bootstrap/arch-linux-bootstrap
@@ -1,5 +1,11 @@
 #!/bin/sh
-# Arch Linux Boostrapping Script (ALBS)
+#     _             _       ____              _       _
+#    / \   _ __ ___| |__   | __ )  ___   ___ | |_ ___| |_ _ __ __ _ _ __
+#   / _ \ | '__/ __| '_ \  |  _ \ / _ \ / _ \| __/ __| __| '__/ _` | '_ \
+#  / ___ \| | | (__| | | | | |_) | (_) | (_) | |_\__ \ |_| | | (_| | |_) |
+# /_/   \_\_|  \___|_| |_| |____/ \___/ \___/ \__|___/\__|_|  \__,_| .__/
+#                                                                  |_|
+#
 # This script installs all programs I need and
 # configures the system to fit my needs.
 #
@@ -9,35 +15,34 @@
 ### OPTIONS AND VARIABLES ### {{{1
 
 # Set default values {{{2
-# TODO: Make sure that the default values are correct
-dotfilesrepo="https://github.com/robert-lag/dotfiles.git"
-progsfile="https://raw.githubusercontent.com/robert-lag/arch-linux-bootstrap/master/programs.csv"
-aurhelper="yay"
-repobranch="master"
+dotfiles_repo="https://github.com/robert-lag/dotfiles.git"
+programs_file_url="https://raw.githubusercontent.com/robert-lag/scripts/master/arch-linux-bootstrap/programs.csv"
+aur_helper="yay"
+dotfiles_repo_branch="master"
 dotfiles_directory=".dotfiles"
 
 # Let the user specify custom values {{{2
 while getopts ":a:r:b:p:h" o; do case "${o}" in
     h) printf "OPTIONS:
     -r    Set dotfiles repository
-          (default: '$dotfilesrepo')
+          (default: '$dotfiles_repo')
     -b    Set branch of dotfiles repository to install
-          (default: '$repobranch')
+          (default: '$dotfiles_repo_branch')
     -p    Set url of *.csv-file describing packages to install
-          (default: '$progsfile')
+          (default: '$programs_file_url')
     -a    Set name of AUR helper to install (must have pacman-like syntax)
-          (default: '$aurhelper')
+          (default: '$aur_helper')
     -d    Set installation directory of dotfiles
           (default: '$dotfiles_directory')
     -h    Show this message
 " && exit 1 ;;
-    r) dotfilesrepo=${OPTARG} &&
-        git ls-remote "$dotfilesrepo" || exit 1 ;;
-    b) repobranch=${OPTARG} ;;
+    r) dotfiles_repo=${OPTARG} &&
+        git ls-remote "$dotfiles_repo" || exit 1 ;;
+    b) dotfiles_repo_branch=${OPTARG} ;;
     d) dotfiles_directory=${OPTARG} ;;
-    p) progsfile=${OPTARG} ;;
-    a) aurhelper=${OPTARG} ;;
-    *) printf "Invalid option: -%s\\n" "$OPTARG" && exit 1 ;;
+    p) programs_file_url=${OPTARG} ;;
+    a) aur_helper=${OPTARG} ;;
+    *) printf "Illegal option: -%s\\n" "$OPTARG" && exit 1 ;;
 esac done
 
 ### }}}1
@@ -55,12 +60,10 @@ error() { # {{{2
 
 show_welcomemsg() { # {{{2
     dialog --title "Welcome!" \
-        --msgbox "Welcome to Robert's Auto-Rice Bootstrapping Script (inspired by LARBS)!
+        --msgbox "Welcome to the Arch-Bootstrap!
 
 This script will automatically setup all dotfiles, scripts and programs which are used
-by myself.
-
--- Robert" 10 60
+by myself." 10 60
 
     dialog --colors --title "Important Note!" \
         --yes-label "All ready!" \
@@ -93,13 +96,13 @@ check_if_user_exists_already() { # {{{2
         dialog --colors --title "WARNING!" \
             --yes-label "CONTINUE" \
             --no-label "No wait..." \
-            --yesno "The user \`$username\` already exists on this system. ALBS can install for a user already existing,
+            --yesno "The user \`$username\` already exists on this system. Arch-Bootstrap can install for an already existing user,
 but it will \\Zboverwrite\\Zn any conflicting settings/dotfiles on the user account.
 
-ALBS will \\Zbnot\\Zn overwrite your user files, documents, videos, etc., so don't worry about that,
+Arch-Bootstrap will \\Zbnot\\Zn overwrite your user files, documents, videos, etc., so don't worry about that,
 but only click <CONTINUE> if you don't mind your settings being overwritten.
 
-Note also that ALBS will change $username's password to the one you just gave." 14 70
+Note also that Arch-Bootstrap will change $username's password to the one you just gave." 14 70
 }
 
 add_user_with_password() { # Adds user `$username` with password $pass1. {{{2
@@ -132,10 +135,10 @@ refresh_keyring() { # {{{2
 
 set_new_sudo_permissions() { # Set special sudoers settings for install (or after). {{{2
     # Delete old permissions in config file if it exists
-    sed --in-place "/# Set by ALBS/d" /etc/sudoers
+    sed --in-place "/# Set by Arch-Bootstrap/d" /etc/sudoers
 
     # Create new line with the new permissions
-    echo "$* # Set by ALBS" >> /etc/sudoers
+    echo "$* # Set by Arch-Bootstrap" >> /etc/sudoers
 }
 
 manual_install() { # Installs $1 manually if not installed {{{2
@@ -151,14 +154,14 @@ manual_install() { # Installs $1 manually if not installed {{{2
 }
 
 main_install() { # Installs specified package ($1) from main repo {{{2
-    dialog --title "ALBS Installation" --infobox "Installing \`$1\` ($package_index of $package_count). $1 $2" 5 70
+    dialog --title "Arch-Bootstrap Installation" --infobox "Installing \`$1\` ($package_index of $package_count). $1 $2" 5 70
     install_pkg "$1"
 }
 
 gitmake_install() { # {{{2
     progname="$(basename "$1" .git)"
     dir="$repodir/$progname"
-    dialog --title "ALBS Installation" --infobox "Installing \`$progname\` ($package_index of $package_count) via \`git\` and \`make\`. $(basename "$1") $2" 5 70
+    dialog --title "Arch-Bootstrap Installation" --infobox "Installing \`$progname\` ($package_index of $package_count) via \`git\` and \`make\`. $(basename "$1") $2" 5 70
     sudo -u "$username" git clone --depth 1 "$1" "$dir" >/dev/null 2>&1 \
         || {
             cd "$dir" || return 1 ;
@@ -171,21 +174,21 @@ gitmake_install() { # {{{2
 }
 
 aur_install() { # {{{2
-    dialog --title "ALBS Installation" --infobox "Installing \`$1\` ($package_index of $package_count) from the AUR. $1 $2" 5 70
+    dialog --title "Arch-Bootstrap Installation" --infobox "Installing \`$1\` ($package_index of $package_count) from the AUR. $1 $2" 5 70
     echo "$aur_installed_programs" | grep -q "^$1$" && return 1
-    sudo -u "$username" $aurhelper -S --noconfirm "$1" >/dev/null 2>&1
+    sudo -u "$username" $aur_helper -S --noconfirm "$1" >/dev/null 2>&1
 }
 
 pip_install() { # {{{2
-    dialog --title "ALBS Installation" --infobox "Installing the Python package \`$1\` ($package_index of $package_count). $1 $2" 5 70
+    dialog --title "Arch-Bootstrap Installation" --infobox "Installing the Python package \`$1\` ($package_index of $package_count). $1 $2" 5 70
     [ -x "$(command -v "pip")" ] || install_pkg python-pip >/dev/null 2>&1
     yes | pip install "$1"
 }
 
 installationloop() { # {{{2
-    ([ -f "$progsfile" ] &&
-        cp "$progsfile" /tmp/progs.csv) ||
-        curl -Ls "$progsfile" | sed '/^[#\/]/d' > /tmp/progs.csv
+    ([ -f "$programs_file_url" ] &&
+        cp "$programs_file_url" /tmp/progs.csv) ||
+        curl -Ls "$programs_file_url" | sed '/^[#\/]/d' > /tmp/progs.csv
     package_count=$(wc -l < /tmp/progs.csv)
     aur_installed_programs=$(pacman -Qqm)
     while IFS=, read -r tag program comment; do
@@ -202,7 +205,7 @@ installationloop() { # {{{2
 
 putgitrepo() { # Downloads a gitrepo $1 and places the files in $2 only overwriting conflicts ($3 is the branch to download (default=master)) {{{2
     dialog --infobox "Downloading and installing config files..." 4 60
-    [ -z "$3" ] && branch="master" || branch="$repobranch"
+    [ -z "$3" ] && branch="master" || branch="$dotfiles_repo_branch"
     dir=$(mktemp --directory)
     [ ! -d "$2" ] && mkdir --parents "$2"
     chown "$username":wheel "$dir" "$2"
@@ -211,7 +214,7 @@ putgitrepo() { # Downloads a gitrepo $1 and places the files in $2 only overwrit
 }
 
 install_dotfiles() { # Installs and stows all dotfiles {{{2
-    putgitrepo "$dotfilesrepo" "/home/$username/$dotfiles_directory" "$repobranch"
+    putgitrepo "$dotfiles_repo" "/home/$username/$dotfiles_directory" "$dotfiles_repo_branch"
 
     # Link all dotfiles to their correct directories (using stow)
     dotfiles_path="/home/robert/.dotfiles"
@@ -223,15 +226,14 @@ install_dotfiles() { # Installs and stows all dotfiles {{{2
     done
 }
 
-finalize() { # {{{2
+show_finish_msg() { # Show finish message {{{2
     dialog --infobox "Preparing welcome message..." 4 50
     dialog --title "All done!" --msgbox "Congrats!
 Provided there were no hidden errors, the script completed successfully and all the programs
 and configuration files should be in place.
-To run the new graphical environment, log out and log back in as your new user, then run the
-command \"startx\" to start the graphical environment (it will start automatically in tty1).\\n\\n.t
 
--- Robert" 12 80
+To run the new graphical environment, log out and log back in as your new user, then run the
+command \"startx\" to start the graphical environment (it will start automatically in tty1)." 12 80
 }
 
 ### }}}1
@@ -282,7 +284,7 @@ refresh_keyring || error "Error automatically refreshing Arch keyring. Consider 
 
 # Install programs needed for installing other programs
 for x in curl base-devel git zsh; do
-    dialog --title "ALBS Installation"
+    dialog --title "Arch-Bootstrap Installation"
            --infobox "Installing \`$x\` which is required to install and configure other programs." 5 70
     install_pkg "$x"
 done
@@ -291,7 +293,7 @@ done
 sed -i "s/-j2/-j$(nproc)/;s/^#MAKEFLAGS/MAKEFLAGS/" /etc/makepkg.conf
 
 # Manually install the AUR helper (further AUR installations can use aur_install)
-manual_install $aurhelper || error "Failed to install AUR helper."
+manual_install $aur_helper || error "Failed to install AUR helper."
 
 ### Autmatic Installation {{{2
 
@@ -319,8 +321,8 @@ EndSection' > /etc/X11/xorg.conf.d/40-libinput.conf
 
 # This line, overwriting the `newperms` command above will allow the user to run
 # serveral important commands, `shutdown`, `reboot`, updating, etc. without a password.
-set_new_sudo_permissions "%wheel ALL=(ALL) ALL # Set by ALBS
+set_new_sudo_permissions "%wheel ALL=(ALL) ALL # Set by Arch-Bootstrap
 %wheel ALL=(ALL) NOPASSWD: /usr/bin/shutdown,/usr/bin/reboot,/usr/bin/systemctl suspend,/usr/bin/wifi-menu,/usr/bin/mount,/usr/bin/umount,/usr/bin/pacman -Syu,/usr/bin/pacman -Syyu,/usr/bin/pacman -Syyu --noconfirm,/usr/bin/loadkeys,/usr/bin/yay,/usr/bin/pacman -Syyuw --noconfirm"
 
-finalize
+show_finish_msg
 clear
